export const ERROR_CODES = {
  COMPANY_OR_OWNER_ALREADY_EXISTS: 'COMPANY_OR_OWNER_ALREADY_EXISTS',

  VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',
  VEHICLE_ALREADY_EXISTS: 'VEHICLE_ALREADY_EXISTS',  

  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  BOOKING_OVERLAP: 'BOOKING_OVERLAP',
  INTERVAL_INVALID: 'INTERVAL_INVALID',
  START_IN_PAST: 'START_IN_PAST',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  NOT_YOUR_RESERATION: 'NOT_YOUR_RESERATION',
  DOES_NOT_START: 'DOES_NOT_START',
  DOES_NOT_COMPLETE: 'DOES_NOT_COMPLETE'
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

export interface ErrorPayload {
  code: ErrorCode;
  message: string;
}
